### ISSUE TITLE
Android Application Feature Request:

### ISSUE THREAD

**Issue by Jpersh27** [gargakshit/passwd#16]
Hello @gargakshit I have listed several specific features below that I believe should be included in the future development of your application.

1.) Import and Export option.

2.) Automatically Create a Backup file every 24 hours or provide a 1 time backup option  whenever you want to create a new backup on your device. Provide option to store it either on your Internal or External storage device in case of app deletion or lost device. 

3.) Store Notes, Cards, identities, Create Folders, and a Trash bin to safely delete unwanted items.

4.) Provide an option to extend the “App Timeout option" Before the app locks on exit. For example: 1 minute, 5 minutes, 15 minutes, 30 minutes, 1 hour, lock immediately on exit, etc...

5.) Expand the Autofill Service to Use the Draw-Over and the Accessibility permissions for Android. (It will significantly help improve the accuracy of form filling for passwords) 

6.) Offer other Dark Mode options besides the current flat black one. (Similar to Bitwarden which offers Black, Dark, Light, and Nord)

**Comment by gargakshit** [comment]
Hello @Jpersh27
I am currently a bit occupied with my college and exams. I will try to get back to developing the app as soon as they are over. Thanks for the feature requests though

**Comment by Jpersh27** [comment]
@gargakshit  You are welcome and thank you for the reply. 

1.) Any time frame on when you will be able to resume app development for the Passwd app?

2.) Any ETA on when you will release a new version of the app? And what all will be included in that upcoming release? 

Thank you again and looking forward to your reply.

**Comment by gargakshit** [comment]
> Any time frame on when you will be able to resume app development for the Passwd app?

Most probably in the first week of May

> Any ETA on when you will release a new version of the app? 

Can't say for certain, but it should be around the end of may.
