### ISSUE TITLE
Translation to Chinese

### ISSUE THREAD

**Issue by huangguiniab** [gargakshit/passwd#17]
Hello!, I like this project, I hope to translate it into Chinese (Simplified Chinese), please add Chinese to crowdin.

**Comment by gargakshit** [comment]
> Hello!, I like this project, I hope to translate it into Chinese (Simplified Chinese), please add Chinese to crowdin.

Thank you for you contributions. I added Chinese simplified in crowdin.

https://crowdin.com/project/passwd

**Comment by huangguiniab** [comment]
Thank you

**Comment by huangguiniab** [comment]
ummmm..I can't find where this sentence is located,  'I am still under construction'   so I can't accurately translate its meaning. Where is this sentence?

**Comment by gargakshit** [comment]
> ummmm..I can't find where this sentence is located, 'I am still under construction' so I can't accurately translate its meaning. Where is this sentence?

It is shown in a "snackbar" when someone tries to use a feature thats not ready yet

**Comment by huangguiniab** [comment]
Thank you.I have completed all the translations, good luck.

**Comment by gargakshit** [comment]
Thank you for your contributions! I will merge them as soon as I get time
