### ISSUE TITLE
The need of change PIN.

### ISSUE THREAD

**Issue by jainamoswal** [gargakshit/passwd#19]
Whenever the **PIN** is compromised, I need to reset my app & my all my password data.
So, It would be great if this app gets the "**Change PIN**" feature.
This app right now is best, but this small feature which can make this project more user-friendly & cooler.

And also to mention that we need a **[Telegram channel](https://github.com/passwdapp/passwd/issues/6#issuecomment-775250384)**/group. 😅

**Comment by gargakshit** [comment]
Hey! Thanks for the kind words.

I'm really sorry, I currently can not continue to work on the app due to personal and college issues. I will try to add it once my college is over.

> And also to mention that we need a Telegram channel/group. 😅

I am really sorry, I don't have enough man-power to maintain a group or channel.

**Comment by jainamoswal** [comment]
> I'm really sorry, I currently can not continue to work on the app due to personal and college issues. I will try to add it once my college is over.
> 
Ok, no problem. Try it once you are free enough. 😉
> I am really sorry, I don't have enough man-power to maintain a group or channel.

Yesterday night, I made a [**channel**](https://t.me/passwdapp) your behalf, and I'll upload this project details. 
Whenever you are able to manage that stuff, [**I'll**](https://t.me/exprexx) transfer the [**channel**](https://t.me/passwdapp) to you. 🙂

Also I'm trying to make a tutorial on how to deploy that box server to add sync feature, and I'm facing few issues maybe cause I don't know any other language than Python so need help. So can you contact me [**here**](https://t.me/exprexx) on Telegram ? 👀

**Comment by gargakshit** [comment]
Thanks for the help! I will ping you on your telegram. Would you mind adding `(unofficial)` in the channel name until I am free to manage it myself.

Thanks again!
