### ISSUE TITLE
[failed to compile] 

### ISSUE THREAD

**Issue by rustzz** [gargakshit/passwd#21]
**Desktop:**
 - OS: Gentoo Desktop
 - Browser: Firefox

`flutter run`: http://dpaste.com/AMYMWPF2S

How compile for linux desktop?

**Comment by gargakshit** [comment]
I haven't upgraded the project and its dependencies to be compatible with newer flutter versions yet due to the lack of time and interest

**Comment by rustzz** [comment]
Where i can download precompiled desktop version?

**Comment by rustzz** [comment]
> I haven't upgraded the project and its dependencies to be compatible with newer flutter versions yet due to the lack of time and interest

ok, which version is compatible?

**Comment by gargakshit** [comment]
> > I haven't upgraded the project and its dependencies to be compatible with newer flutter versions yet due to the lack of time and interest
> 
> ok, which version is compatible?

I think the latest version of flutter 1.x should be compatible.

**Comment by rustzz** [comment]
Yes, I checked the last release date of your app and the release date of Flutter. After that, my PC did not show as a device (an empty list).
I tried version 2.0.0 (but the application was built using wayland, but I have Xorg)

Maybe you have precompiled binaries?

**Comment by rustzz** [comment]
it's just that I somehow tried to compile a custom kernel for a smartphone and the maintainer forgot to add the vendor files. and they were on an old hard drive, maybe you also have them somewhere?

p.s.: by the way, this [commit](https://github.com/nikp123/Xiaomi_Kernel_OpenSource/commit/7293318960d68f1dc3458606422e87fc24823491) with the addition of files

**Comment by ghost** [comment]
**_Hi @gargakshit, So you mean that for versions 2.x > <3.x no binary has been built? Only in version 1.x_**

> > > I haven't upgraded the project and its dependencies to be compatible with newer flutter versions yet due to the lack of time and interest
> > 
> > 
> > ok, which version is compatible?
> 
> I think the latest version of flutter 1.x should be compatible.

**Comment by gargakshit** [comment]
> **_Hi @gargakshit, So you mean that for versions 2.x > <3.x no binary has been built? Only in version 1.x_**
> 
> > > > I haven't upgraded the project and its dependencies to be compatible with newer flutter versions yet due to the lack of time and interest
> > > 
> > > 
> > > ok, which version is compatible?
> > 
> > I think the latest version of flutter 1.x should be compatible.
> 
> 

That is correct

**Comment by ghost** [comment]
> > **_Hi @gargakshit, So you mean that for versions 2.x > <3.x no binary has been built? Only in version 1.x_**
> > > > > I haven't upgraded the project and its dependencies to be compatible with newer flutter versions yet due to the lack of time and interest
> > > > 
> > > > 
> > > > ok, which version is compatible?
> > > 
> > > 
> > > I think the latest version of flutter 1.x should be compatible.
> 
> That is correct

Ok bro @gargakshit, thanks, One additional question, what do I need to build on linux/android?
Any special dependency?

**Comment by gargakshit** [comment]
> > > **_Hi @gargakshit, So you mean that for versions 2.x > <3.x no binary has been built? Only in version 1.x_**
> > > > > > I haven't upgraded the project and its dependencies to be compatible with newer flutter versions yet due to the lack of time and interest
> > > > > 
> > > > > 
> > > > > ok, which version is compatible?
> > > > 
> > > > 
> > > > I think the latest version of flutter 1.x should be compatible.
> > 
> > That is correct
> 
> Ok bro @gargakshit, thanks, One additional question, what do I need to build on linux/android?
> Any special dependency?

Nope, other than the dependencies for flutter and Android

**Comment by ghost** [comment]
> Nope, other than the dependencies for flutter and Android

Ok bro, I'll try to migrate to version >=2.17 <=3.0.5 and each of the dependencies and add support with kdbx
