### ISSUE TITLE
Continue work on this project

### ISSUE THREAD

**Issue by Akul2010** [gargakshit/passwd#23]
Hi,

Can I edit and continue work on this project? I want to make my own password manager someday, and this will definitely help.

Thanks!

**Comment by gargakshit** [comment]
Yep, you are welcome to fork the project as long as you adhere to the `LICENSE`

**Comment by rustzz** [comment]
> Hi,
> 
> Can I edit and continue work on this project? I want to make my own password manager someday, and this will definitely help.
> 
> Thanks!

hi, what do you think if we rewrite the client together?

I've only been teaching flutter for a month and have written my own version of the client

if you have more experience than me. could you help me refactor the code in a nice way?

it remains to get/analyze the server api for this client and send requests to it

[Check my repo](https://github.com/rustzz/passwd)

**Comment by rustzz** [comment]
or pm me
Telegram: @rustzz

**Comment by Akul2010** [comment]
Hey rustzz, that would be great! I don't have telegram, though.

**Comment by rustzz** [comment]
@Akul2010 where we may chatting?

**Comment by Akul2010** [comment]
I don't really have too many options... for now, just google or discord

**Comment by rustzz** [comment]
send your discord id

**Comment by Akul2010** [comment]
Winner#1942 (i made the name when i was big on gaming, please don't judge me)

**Comment by rustzz** [comment]
![Screenshot_20220817-230049_Aliucord.png](https://user-images.githubusercontent.com/74064444/185210165-f4b422da-b8e1-4bce-a48c-177f285b9a59.png)

My ID rustzz#1825

**Comment by Akul2010** [comment]
Sorry, typo. It's actually Winner#1924

**Comment by Akul2010** [comment]
I sent friend request to you.
