### ISSUE TITLE
Question about internet permission

### ISSUE THREAD

**Issue by ghost** [gargakshit/passwd#26]
**Describe the bug**
Whenever i add password entry, it sends request to `i.olsh.me`. Please explain why this request are sent.

**Expected behavior**
There should be no internet traffic for this app

**Screenshots**
![SmartSelect_20231125-163646_Rethink](https://github.com/passwdapp/passwd/assets/142499381/b7540278-2336-4e74-8eb7-dc196d3c1242)

**Desktop (please complete the following information):**
 - OS: Android 11

**Comment by gargakshit** [comment]
`i.olsh.me` was used to grab the icons for a website. Relevant code:

https://github.com/passwdapp/passwd/blob/develop/lib/services/favicon/favicon_new.dart#L14-L19

PS: Passwdapp has been deprecated. I don't recommend using it anymore.
