### ISSUE TITLE
App Build Error

### ISSUE THREAD

**Issue by shreekrishnalamichhane** [gargakshit/passwd#5]
Hi,
When I try to build the .apk file I get an error like this.

> Note: Some input files use unchecked or unsafe operations.
> Note: Recompile with -Xlint:unchecked for details.
> Running Gradle task 'assembleDebug'...
> Running Gradle task 'assembleDebug'... Done                       116.2s
> Exception: Gradle build failed to produce an .apk file. It's likely that this file was generated under 
> C:\Users\username\Desktop\passwd\build, but the tool couldn't find it.

How can I solve that??

**Comment by gargakshit** [comment]
Looks like some issue with your SDK, please try upgrading / or re-installing. Also, please check the build folder if the APK is produced
