### ISSUE TITLE
{Q} Server URL and self-host?

### ISSUE THREAD

**Issue by mizzunet** [gargakshit/passwd#6]
What's server URL for signing up and can I self-host, Heroku maybe? And you got Telegram group/channel for Passwd? If yes, please share 
Thanks

**Comment by gargakshit** [comment]
Currently we do not provide a hosted instance, though you can self-host it. It requires persistent storage (to store your encrypted data and the sqlite database), so I don't think heroku will do the trick.

You can read the (currently incomplete) documentation about building the server [here](https://github.com/passwdapp/box)

**Comment by gargakshit** [comment]
> And you got Telegram group/channel for Passwd?

I currently don't have any group / channel for Passwd, but I am looking to make one. I will update here about the same

**Comment by mizzunet** [comment]
> Currently we do not provide a hosted instance, though you can self-host it. It requires persistent storage (to store your encrypted data and the sqlite database), so I don't think heroku will do the trick.
> 
> You can read the (currently incomplete) documentation about building the server [here](https://github.com/passwdapp/box)

Thanks, yeah it seems incomplete :D, hasn't what are the variables. And I have hosted BitWarden in Heroku that uses my DB from freedb.tech (https://github.com/davidjameshowell/bitwarden_rs_heroku). It would be great if there's Heroku deployment support, because it's free. Thank you so much for this awesome project. Looking forward to it. Good luck

**Comment by mizzunet** [comment]
> > And you got Telegram group/channel for Passwd?
> 
> I currently don't have any group / channel for Passwd, but I am looking to make one. I will update here about the same

Thanks. Having a telegram group and channel can have more audience :)

**Comment by gargakshit** [comment]
> > Currently we do not provide a hosted instance, though you can self-host it. It requires persistent storage (to store your encrypted data and the sqlite database), so I don't think heroku will do the trick.
> > You can read the (currently incomplete) documentation about building the server [here](https://github.com/passwdapp/box)
> 
> Thanks, yeah it seems incomplete :D, hasn't what are the variables. And I have hosted BitWarden in Heroku that uses my DB from freedb.tech ([davidjameshowell/bitwarden_rs_heroku](https://github.com/davidjameshowell/bitwarden_rs_heroku)). It would be great if there's Heroku deployment support, because it's free. Thank you so much for this awesome project. Looking forward to it. Good luck

I will surely look into ways to make it heroku compatible. The variables are the environment variables as given in the `.env.sample` file :)

**Comment by mizzunet** [comment]
> > > Currently we do not provide a hosted instance, though you can self-host it. It requires persistent storage (to store your encrypted data and the sqlite database), so I don't think heroku will do the trick.
> > > You can read the (currently incomplete) documentation about building the server [here](https://github.com/passwdapp/box)
> > 
> > 
> > Thanks, yeah it seems incomplete :D, hasn't what are the variables. And I have hosted BitWarden in Heroku that uses my DB from freedb.tech ([davidjameshowell/bitwarden_rs_heroku](https://github.com/davidjameshowell/bitwarden_rs_heroku)). It would be great if there's Heroku deployment support, because it's free. Thank you so much for this awesome project. Looking forward to it. Good luck
> 
> I will surely look into ways to make it heroku compatible. The variables are the environment variables as given in the `.env.sample` file :)

I haven seen that but but can't understand why each variable is for except MAX_USERS which is self-explanatory :)
I hope I'm not disturbing you :P

**Comment by gargakshit** [comment]
> I haven seen that but but can't understand why each variable is for except MAX_USERS which is self-explanatory :)

It is to restrict the number of users registered on one instance.

> I hope I'm not disturbing you :P

No you are not disturbing me :)

**Comment by mizzunet** [comment]
> > I haven seen that but but can't understand why each variable is for except MAX_USERS which is self-explanatory :)
> 
> It is to restrict the number of users registered on one instance.
> 
> > I hope I'm not disturbing you :P
> 
> No you are not disturbing me :)

What other variables represent?
> No you are not disturbing me :)
<3

**Comment by gargakshit** [comment]
> > > I haven seen that but but can't understand why each variable is for except MAX_USERS which is self-explanatory :)
> > 
> > 
> > It is to restrict the number of users registered on one instance.
> > > I hope I'm not disturbing you :P
> > 
> > 
> > No you are not disturbing me :)
> 
> What other variables represent?
> 
> > No you are not disturbing me :)
> > <3

`SECRET_KEY` - Its a secret shared between users of a particular instance. It is used to prevent spammers or potentially unauthorized users to register on your instance

`JWT_TOKEN` - This is used to sign the authentication tokens, so don't share it with anyone, and keep it super long and unique

`MAX_USERS` - Used to limit the maximum users registered on an instance

`LISTEN_ADDRESS` - The HTTP address to listen on. For example `0.0.0.0:3000` means listen the HTTP server on all interfaces and port 3000, while `127.0.0.1:5000` means listen only on the loopback interface on port 5000

**Comment by gargakshit** [comment]
passwdapp/box#2
